//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WT.Resources.FileTranslation", typeof(FileTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1} Credits.
        /// </summary>
        public static string AnswerAlienToCredits {
            get {
                return ResourceManager.GetString("AnswerAlienToCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}.
        /// </summary>
        public static string AnswerAlienToNumber {
            get {
                return ResourceManager.GetString("AnswerAlienToNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have no idea what you are talking about.
        /// </summary>
        public static string AnswerNoIdea {
            get {
                return ResourceManager.GetString("AnswerNoIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^how many Credits is ([\w ]+) \?$.
        /// </summary>
        public static string AskAlienToCredits {
            get {
                return ResourceManager.GetString("AskAlienToCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^how much is ([\w ]+) \?$.
        /// </summary>
        public static string AskAlienToNumber {
            get {
                return ResourceManager.GetString("AskAlienToNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([\w ]+) is ([\d\.\,]+) Credits$.
        /// </summary>
        public static string TranslateAlienToCredits {
            get {
                return ResourceManager.GetString("TranslateAlienToCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\w+) is ([IVXLCDM])$.
        /// </summary>
        public static string TranslateAlienToRoman {
            get {
                return ResourceManager.GetString("TranslateAlienToRoman", resourceCulture);
            }
        }
    }
}
